// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvjnMqw5uq8YtGmEWgQQGU4iFRyLA1FY',
    appId: '1:991912517006:web:10cef3710202051ab758df',
    messagingSenderId: '991912517006',
    projectId: 'delivery-22ad8',
    authDomain: 'delivery-22ad8.firebaseapp.com',
    storageBucket: 'delivery-22ad8.appspot.com',
    measurementId: 'G-1JEKP8J5JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Kb7oqjpN3EfYLYOyBj8dNRI7QbQs3Zs',
    appId: '1:991912517006:android:de5397ce93ef6d60b758df',
    messagingSenderId: '991912517006',
    projectId: 'delivery-22ad8',
    storageBucket: 'delivery-22ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38xmFG98FdGLtM8n1uoM_LhkpG1IbKbI',
    appId: '1:991912517006:ios:16df54345f69d652b758df',
    messagingSenderId: '991912517006',
    projectId: 'delivery-22ad8',
    storageBucket: 'delivery-22ad8.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38xmFG98FdGLtM8n1uoM_LhkpG1IbKbI',
    appId: '1:991912517006:ios:7024698c80a428bbb758df',
    messagingSenderId: '991912517006',
    projectId: 'delivery-22ad8',
    storageBucket: 'delivery-22ad8.appspot.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
